### ISSUE TITLE
量化后保存的模型参数仍然为浮点数？

### ISSUE THREAD

**Issue by timoycao** [Tencent/PocketFlow#205]
learner选取为uniform，再次训练后得到的模型并不是int类型参数，所以uniform的learner只是在计算过程中使用了量化，但并没有输出量化后的模型是吗？uniform支持训练后直接保存int类型参数吗？

**Comment by jiaxiang-wu** [comment]
Yes, `UniformQuantLearner` (not `UniformQuantTFLearner`) uses quantization during training but does not output a quantized model. In order to export a *.tflite model with uint8 data type, you need to use `UniformQuantTFLearner`.

**Comment by timoycao** [comment]
> Yes, `UniformQuantLearner` (not `UniformQuantTFLearner`) uses quantization during training but does not output a quantized model. In order to export a *.tflite model with uint8 data type, you need to use `UniformQuantTFLearner`.

I got it. I am now using 'tools/conversion/export_quant_tflite_model.py' to convert trained uqtf model into *.tflite. However I got following messages with 'enbl_post_quant' enabled :
Several Warnings: 
/conv2d/kernel lacks MinMax information.
/batch_normalization_2/FusedBatchNorm_mul_0_param lacks MinMax information. etc.
and an Error:
Unimplemented: this graph contains an operator of type Mean for which the quantized form is not yet implemented.

**Comment by jiaxiang-wu** [comment]
Which model are you using? ResNet?

**Comment by timoycao** [comment]
Details:
WARNING:tensorflow:From /usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
2019-01-22 09:39:47.270423: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-22 09:39:47.283057: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 401 operators, 600 arrays (0 quantized)
2019-01-22 09:39:47.286539: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 401 operators, 600 arrays (0 quantized)
2019-01-22 09:39:47.301075: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 76 operators, 146 arrays (1 quantized)
2019-01-22 09:39:47.301787: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before pre-quantization graph transformations: 76 operators, 146 arrays (1 quantized)
2019-01-22 09:39:47.302101: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After pre-quantization graph transformations pass 1: 58 operators, 128 arrays (1 quantized)
2019-01-22 09:39:47.302456: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before default min-max range propagation graph transformations: 58 operators, 128 arrays (1 quantized)
2019-01-22 09:39:47.302701: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before quantization graph transformations: 58 operators, 128 arrays (1 quantized)
2019-01-22 09:39:47.302715: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/conv2d/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.302734: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/conv2d_1/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.302801: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/batch_normalization_2/FusedBatchNorm_mul_0_param lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.302815: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/batch_normalization_2/FusedBatchNorm_add_param lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.302878: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/batch_normalization_4/FusedBatchNorm_mul_0_param lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.302893: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/batch_normalization_4/FusedBatchNorm_add_param lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.302954: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/batch_normalization_6/FusedBatchNorm_mul_0_param lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.302967: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/batch_normalization_6/FusedBatchNorm_add_param lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.302985: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/conv2d_8/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.303097: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/batch_normalization_8/FusedBatchNorm_mul_0_param lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.303111: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/batch_normalization_8/FusedBatchNorm_add_param lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.303235: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/batch_normalization_10/FusedBatchNorm_mul_0_param lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.303249: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/batch_normalization_10/FusedBatchNorm_add_param lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.303374: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/batch_normalization_12/FusedBatchNorm_mul_0_param lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.303388: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/batch_normalization_12/FusedBatchNorm_add_param lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.303404: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/conv2d_15/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.303725: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/batch_normalization_14/FusedBatchNorm_mul_0_param lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.303739: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/batch_normalization_14/FusedBatchNorm_add_param lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.304251: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/batch_normalization_16/FusedBatchNorm_mul_0_param lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.304266: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/batch_normalization_16/FusedBatchNorm_add_param lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.304659: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/batch_normalization_18/FusedBatchNorm_mul_0_param lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.304672: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:145] Constant array quant_model/resnet_model/batch_normalization_18/FusedBatchNorm_add_param lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-01-22 09:39:47.304683: F tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:519] Unimplemented: this graph contains an operator of type Mean for which the quantized form is not yet implemented. Sorry, and patches welcome (that's a relatively fun patch to write, mostly providing the actual quantized arithmetic code for this op).

and then got error information for generating *.pb files:
Traceback (most recent call last):
  File "tools/conversion/export_quant_tflite_model.py", line 262, in main
    export_pb_tflite_model(net, file_path_meta, file_path_pb, file_paths_tflite)
  File "tools/conversion/export_quant_tflite_model.py", line 233, in export_pb_tflite_model
    test_tflite_model(file_paths_tflite['float'], net['input_data'])
  File "tools/conversion/export_quant_tflite_model.py", line 136, in test_tflite_model
    interpreter.allocate_tensors()
  File "/home/ycao/.local/lib/python3.6/site-packages/tensorflow/contrib/lite/python/interpreter.py", line 66, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/home/ycao/.local/lib/python3.6/site-packages/tensorflow/contrib/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 106, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
ValueError: Interpreter was not initialized.

**Comment by timoycao** [comment]
> The default ResNet-20 model cannot be fully quantized using TensorFlow's quantization-aware training APIs, due to its graph matching pattern. We have added support for manually inserting quantization operations into ResNet models (with `uqtf_enbl_manual_quant` enabled), so that the resulting *.ckpt file can be converted into *.tflite model with uint8 data type.

Actually I can't find attribute `uqtf_enbl_manual_quant` in FLAGS. And I tried training with :
`./scripts/run_local.sh nets/resnet_at_cifar10_run.py --learner uniform-tf --uqtf_enbl_manual_quant=True`
Then I try to convert new model to tflite. Such error still exsists.
Could you give a more specific guide or example of generating an pocketflow ResNet tflite model?

**Comment by jiaxiang-wu** [comment]
Are you using the latest version? This FLAGS is added in the PR merged yesterday.

**Comment by timoycao** [comment]
...I just updated and found this attribute. But how to use it? I tried
‘./scripts/run_local.sh nets/resnet_at_cifar10_run.py --learner uniform-tf --uqtf_enbl_manual_quant
’
get error：
F tensorflow/contrib/lite/toco/tooling_util.cc:1320] Array quant_model/resnet_model/batch_normalization/FusedBatchNorm_mul_0, which is an input to the Add operator producing the output array quant_model/resnet_model/Relu, is lacking min/max data, which is necessary for quantization. Either target a non-quantized output format, or change the input graph to contain min/max information, or pass --default_ranges_min= and --default_ranges_max= if you do not care about the accuracy of results.

Then I use
'./scripts/run_local.sh nets/resnet_at_cifar10_run.py \
    --learner uniform-tf \
    --uqtf_enbl_manual_quant \
    --default_ranges_min 0 \
    --default_ranges_max 6 '

get the same error.
Seems fail to pass attribute into scripts.

**Comment by jiaxiang-wu** [comment]
Sorry, I forgot to mention that you also need to disable the `enbl_fused_batchnorm` FLAGS. By default, ResNet models fuse operations in the batch normalization layer, while manually inserting quantization operation only works when these operations are not fused. So, the command line should be like:
``` bash
$ ./scripts/run_local.sh nets/resnet_at_cifar10_run.py \
    --learner=uniform-tf \
    --uqtf_enbl_manual_quant=True \
    --enbl_fused_batchnorm=False
```

**Comment by jiaxiang-wu** [comment]
If `uqtf_enbl_manual_quant` is enabled, the program will try to convert *.ckpt model to *.tflite model and detect if there is any unquantized node. If yes, this node will be added to the list that manual quantization operations should be inserted. This process may take some time, and after a complete success conversion is done, the training process will begin. For ResNet-20, this process should take about 10 minutes. If you are not sure, please post the log for `uqtf_enbl_manual_quant` is enabled.

**Comment by timoycao** [comment]
> If `uqtf_enbl_manual_quant` is enabled, the program will try to convert *.ckpt model to *.tflite model and detect if there is any unquantized node. If yes, this node will be added to the list that manual quantization operations should be inserted. This process may take some time, and after a complete success conversion is done, the training process will begin. For ResNet-20, this process should take about 10 minutes. If you are not sure, please post the log for `uqtf_enbl_manual_quant` is enabled.

I found the reason. Some internal steps use python however my python was linked with python2. It works after I linked python with python3. Thank you.
By the way, is it possible to extract internal results like feature maps from the compressed model for debug?

**Comment by jiaxiang-wu** [comment]
Of course you can, but you may need to manually code for this. The current repo does not have such feature.

**Comment by timoycao** [comment]
Thank you again and this issue can be closed.
