### ISSUE TITLE
issues:transfer the VOC  dataset to tfrecords format 

### ISSUE THREAD

**Issue by victorywkq** [Tencent/PocketFlow#208]
when i will @transfer the VOC  dataset to tfrecords format ,the issues are follows:
how to solve the issues   @@,tks.
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "dataset/convert_tfrecords.py", line 286, in _process_image_files_batch
    writer = tf.python_io.TFRecordWriter(output_file)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/tf_record.py", line 210, in __init__
    compat.as_bytes(path), options._as_record_writer_options(), status)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ./datasets/tfrecords/train-00000-of-00016; No such file or directory

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "dataset/convert_tfrecords.py", line 286, in _process_image_files_batch
    writer = tf.python_io.TFRecordWriter(output_file)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/tf_record.py", line 210, in __init__
    compat.as_bytes(path), options._as_record_writer_options(), status)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ./datasets/tfrecords/train-00006-of-00016; No such file or directory

Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "dataset/convert_tfrecords.py", line 286, in _process_image_files_batch
    writer = tf.python_io.TFRecordWriter(output_file)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/tf_record.py", line 210, in __init__
    compat.as_bytes(path), options._as_record_writer_options(), status)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ./datasets/tfrecords/train-00014-of-00016; No such file or directory

**Comment by victorywkq** [comment]
add to the above issues: 
the command is copied  from the readme doc :Run the following script to generate TFRecords.
	python dataset/convert_tfrecords.py --dataset_directory=VOCROOT --output_directory=./datasets/tfrecords
the VOC dataset directory is :/PocketFlow-master/utils/external/ssd_tensorflow/VOCROOT

**Comment by wangxianrui** [comment]
make sure that the output_directory `./datasets/tfrecords` exist

**Comment by jiaxiang-wu** [comment]
@victorywkq Is your issue resolved using @wangxianrui 's suggestion?
