### ISSUE TITLE
there's an AttributeError when I compress ssd model by uniform 

### ISSUE THREAD

**Issue by XY-Yoalnda** [Tencent/PocketFlow#222]
command line:
./scripts/run_docker.sh nets/vgg_at_pascalvoc_run.py --learner uniform

Traceback (most recent call last):
  File "main.py", line 69, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 51, in main
    learner = create_learner(sm_writer, model_helper)
  File "/opt/ml/env/learners/learner_utils.py", line 55, in create_learner
    learner = UniformQuantLearner(sm_writer, model_helper)
  File "/opt/ml/env/learners/uniform_quantization/learner.py", line 92, in __init__
    self.__build_train()  # for train
  File "/opt/ml/env/learners/uniform_quantization/learner.py", line 193, in __build_train
    images.set_shape((FLAGS.batch_size, images.shape[1], images.shape[2],
AttributeError: 'dict' object has no attribute 'set_shape'

**Comment by jiaxiang-wu** [comment]
Sorry for the late reply.
For uniform quantization on SSD models, use `UniformQuantTFLearner` instead of `UniformQuantLearner`. This `AttributeError` is caused by the different data input pipeline between SSD models and other ModelHelpers, *e.g.* ResNet on CIFAR-10/ILSVRC-12. The former one returns two dictionaries while the latter one returns two tensors.
