### ISSUE TITLE
question about dis-chn-pruned learner

### ISSUE THREAD

**Issue by huanyingjun** [Tencent/PocketFlow#254]
Hi , 
我在训练一个SuperResolution模型，使用dis-chn-pruned 进行剪枝。
模型的loss ： loss = tf.reduce_mean(tf.losses.absolute_difference(target, outputs))
请问在 discr_channel_pruning/learner.py中的 __build_extra_losses 中怎么计算 dis_losses ？

请问对于PockeFlow的这段代码该怎么修改？
```c++
        x = core_ops_prnd[idx_layer].outputs[0]
        x = tf.layers.batch_normalization(x, axis=3, training=True)
        x = tf.nn.relu(x)
        x = tf.reduce_mean(x, axis=[1, 2])
        x = tf.layers.dense(x, FLAGS.nb_classes)
        dis_losses += [tf.losses.softmax_cross_entropy(labels, x)]
```

谢谢

**Comment by jiaxiang-wu** [comment]
You need to change the last line in your posted code, and replace softmax loss with your loss function.

**Comment by huanyingjun** [comment]
Hi，我把loss改成了如下：
```c++
        x = core_ops_prnd[idx_layer].outputs[0]
        x = tf.layers.batch_normalization(x, axis=3, training=True)
        x = tf.nn.relu(x)
        #x = tf.reduce_mean(x, axis=[1, 2])
        #x = tf.layers.dense(x, FLAGS.nb_classes)
        dis_losses += [tf.reduce_mean(tf.losses.absolute_difference(x , labels ))]
```
但是有问题，x的shape 是(?, 48, 48, 64) ， 而labels的shape 是(?, 144, 144, 3)
log如下
```c++
Traceback (most recent call last):
  File "main.py", line 51, in main
    learner = create_learner(sm_writer, model_helper)
  File "/home/ mingli/work/PocketFlow/learners/learner_utils.py", line 56, in create_learner
    learner = DisChnPrunedLearner(sm_writer, model_helper)
  File "/home/ mingli/work/PocketFlow/learners/discr_channel_pruning/learner.py", line 126, in __init__
    self.__build_train()
  File "/home/ mingli/work/PocketFlow/learners/discr_channel_pruning/learner.py", line 252, in __build_train
    self.__build_extra_losses(labels)
  File "/home/ mingli/work/PocketFlow/learners/discr_channel_pruning/learner.py", line 373, in __build_extra_losses
    dis_losses += [tf.reduce_mean(tf.losses.absolute_difference(x , labels ))]
  File "/home/ mingli/anaconda2/lib/python3.6/site-packages/tensorflow/python/ops/losses/losses_impl.py", line 282, in absolute_difference
    predictions.get_shape().assert_is_compatible_with(labels.get_shape())
  File "/home/ mingli/anaconda2/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 848, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (?, 144, 144, 3) and (?, 48, 48, 64) are incompatible
```

**Comment by jiaxiang-wu** [comment]
It seems the "x" for loss computation is not the final output of your SuperResolution model. Can you check the shape of output tensor of the `forward_fn` function in your self-defined `ModelHelper`?

**Comment by huanyingjun** [comment]
thanks
