### ISSUE TITLE
Download Pretrain Model But Get 502 Bad Gateway Error

### ISSUE THREAD

**Issue by A1exy** [Tencent/PocketFlow#313]
Use official code to Uniform Quantization, But Get 502 Bad Gateway Error.

Quantized: model/resnet_model/Relu_18/uniform_quantize
--2019-09-19 16:08:10--  https://api.ai.tencent.com/pocketflow/models_resnet_20_at_cifar_10.tar.gz
Resolving api.ai.tencent.com (api.ai.tencent.com)... 61.151.164.80
Connecting to api.ai.tencent.com (api.ai.tencent.com)|61.151.164.80|:443... connected.
HTTP request sent, awaiting response... 502 Bad Gateway
2019-09-19 16:08:10 ERROR 502: Bad Gateway.

Traceback (most recent call last):
  File "main.py", line 69, in <module>
    tf.app.run()
  File "/home/hpc/anaconda3/envs/ccx_PF/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 51, in main
    learner = create_learner(sm_writer, model_helper)
  File "/home/hpc/ccx/code/Model_Compress/PocketFlow/learners/learner_utils.py", line 62, in create_learner
    learner = NonUniformQuantLearner(sm_writer, model_helper)
  File "/home/hpc/ccx/code/Model_Compress/PocketFlow/learners/nonuniform_quantization/learner.py", line 99, in __init__
    self.download_model()
  File "/home/hpc/ccx/code/Model_Compress/PocketFlow/learners/abstract_learner.py", line 125, in download_model
    'pre-trained model not avaialable: {} / {}'.format(self.model_name, self.dataset_name))
FileNotFoundError: pre-trained model not avaialable: resnet_20 / cifar_10

**Comment by A1exy** [comment]
https://github.com/Tencent/PocketFlow/issues/293#issuecomment-533936975
