### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by CoderGenJ** [Tencent/PocketFlow#322]
**Describe the bug**
Background:
The ssd-vgg-16 model is pruned by learner chn-pruned-rmt method and have been fine trained 120000 iters.It makes a dir named models_cpr_eval to strore the final pruned-trained models.
BUG:
When i used the export_pb_tflite_models.py script to export a ssd-vgg-16 model to pb file.I get the IndexError.
command:
python export_pb_tflite_models.py --model_dir=../../models_cpr_eval --input_coll=images_final --output_coll=logits_final
Bug log:
"""Traceback (most recent call last):
  File "export_pb_tflite_models.py", line 392, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "export_pb_tflite_models.py", line 371, in main
    input_name, input_shape = get_input_name_n_shape(meta_path)
  File "export_pb_tflite_models.py", line 82, in get_input_name_n_shape
    net_input = tf.get_collection(FLAGS.input_coll)[0]
IndexError: list index out of range
"""
Could you please tell me how to solve this problem?Thanks you in advance.

**Comment by diligent321** [comment]
Hi, did you solved it ? @SLAMgreen 

I meet the save error, appreciated your kind reply !

**Comment by gyx1qaz** [comment]
> **Describe the bug**
> Background:
> The ssd-vgg-16 model is pruned by learner chn-pruned-rmt method and have been fine trained 120000 iters.It makes a dir named models_cpr_eval to strore the final pruned-trained models.
> BUG:
> When i used the export_pb_tflite_models.py script to export a ssd-vgg-16 model to pb file.I get the IndexError.
> command:
> python export_pb_tflite_models.py --model_dir=../../models_cpr_eval --input_coll=images_final --output_coll=logits_final
> Bug log:
> """Traceback (most recent call last):
> File "export_pb_tflite_models.py", line 392, in
> tf.app.run()
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
> _sys.exit(main(argv))
> File "export_pb_tflite_models.py", line 371, in main
> input_name, input_shape = get_input_name_n_shape(meta_path)
> File "export_pb_tflite_models.py", line 82, in get_input_name_n_shape
> net_input = tf.get_collection(FLAGS.input_coll)[0]
> IndexError: list index out of range
> """
> Could you please tell me how to solve this problem?Thanks you in advance.



> **Describe the bug**
> Background:
> The ssd-vgg-16 model is pruned by learner chn-pruned-rmt method and have been fine trained 120000 iters.It makes a dir named models_cpr_eval to strore the final pruned-trained models.
> BUG:
> When i used the export_pb_tflite_models.py script to export a ssd-vgg-16 model to pb file.I get the IndexError.
> command:
> python export_pb_tflite_models.py --model_dir=../../models_cpr_eval --input_coll=images_final --output_coll=logits_final
> Bug log:
> """Traceback (most recent call last):
> File "export_pb_tflite_models.py", line 392, in
> tf.app.run()
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
> _sys.exit(main(argv))
> File "export_pb_tflite_models.py", line 371, in main
> input_name, input_shape = get_input_name_n_shape(meta_path)
> File "export_pb_tflite_models.py", line 82, in get_input_name_n_shape
> net_input = tf.get_collection(FLAGS.input_coll)[0]
> IndexError: list index out of range
> """
> Could you please tell me how to solve this problem?Thanks you in advance.

**Comment by gyx1qaz** [comment]
解决了吗？
