### ISSUE TITLE
tensorflow.python.framework.errors_impl.FailedPreconditionError: Bad file descriptor

### ISSUE THREAD

**Issue by dhingratul** [Tencent/PocketFlow#47]
**Describe the bug**
When running the channel pruning tutorial in local mode, i get the following error

```
Traceback (most recent call last):
  File "/home/dhingratul/.virtualenvs/pocketflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/dhingratul/.virtualenvs/pocketflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/dhingratul/.virtualenvs/pocketflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: /mnt/cifs/public_datasets/imagenet-data/train-00876-of-01024; Bad file descriptor
	 [[Node: data/IteratorGetNext = IteratorGetNext[output_shapes=[[?,224,224,3], [?,1001]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](data/OneShotIterator)]]
	 [[Node: data/IteratorGetNext/_1885 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_155_data/IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 69, in <module>
    tf.app.run()
  File "/home/dhingratul/.virtualenvs/pocketflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 55, in main
    learner.train()
  File "/home/dhingratul/OneDrive/Projects/PocketFlow/learners/discr_channel_pruning/learner.py", line 145, in train
    self.__choose_discr_chns()
  File "/home/dhingratul/OneDrive/Projects/PocketFlow/learners/discr_channel_pruning/learner.py", line 511, in __choose_discr_chns
    self.sess_train.run(self.layer_train_ops[idx_layer])
  File "/home/dhingratul/.virtualenvs/pocketflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/dhingratul/.virtualenvs/pocketflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/dhingratul/.virtualenvs/pocketflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/dhingratul/.virtualenvs/pocketflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: /mnt/cifs/public_datasets/imagenet-data/train-00876-of-01024; Bad file descriptor
	 [[Node: data/IteratorGetNext = IteratorGetNext[output_shapes=[[?,224,224,3], [?,1001]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](data/OneShotIterator)]]
	 [[Node: data/IteratorGetNext/_1885 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_155_data/IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'data/IteratorGetNext', defined at:
  File "main.py", line 69, in <module>
    tf.app.run()
  File "/home/dhingratul/.virtualenvs/pocketflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 51, in main
    learner = create_learner(sm_writer, model_helper)
  File "/home/dhingratul/OneDrive/Projects/PocketFlow/learners/learner_utils.py", line 50, in create_learner
    learner = DisChnPrunedLearner(sm_writer, model_helper)
  File "/home/dhingratul/OneDrive/Projects/PocketFlow/learners/discr_channel_pruning/learner.py", line 127, in __init__
    self.__build_train()
  File "/home/dhingratul/OneDrive/Projects/PocketFlow/learners/discr_channel_pruning/learner.py", line 195, in __build_train
    images, labels = iterator.get_next()
  File "/home/dhingratul/.virtualenvs/pocketflow/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 410, in get_next
    name=name)), self._output_types,
  File "/home/dhingratul/.virtualenvs/pocketflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2069, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/home/dhingratul/.virtualenvs/pocketflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/dhingratul/.virtualenvs/pocketflow/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/dhingratul/.virtualenvs/pocketflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/dhingratul/.virtualenvs/pocketflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): /mnt/cifs/public_datasets/imagenet-data/train-00876-of-01024; Bad file descriptor
	 [[Node: data/IteratorGetNext = IteratorGetNext[output_shapes=[[?,224,224,3], [?,1001]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](data/OneShotIterator)]]
	 [[Node: data/IteratorGetNext/_1885 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_155_data/IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jiaxiang-wu** [comment]
How did  you convert ImageNet to *.tfrecord files? And, can you verify whether this file exists (and its file permission allows reading)?
`/mnt/cifs/public_datasets/imagenet-data/train-00876-of-01024`

**Comment by jiaxiang-wu** [comment]
I'm not sure what exactly caused that error. Can you run other TensorFlow training programs (not PocketFlow) with your ImageNet *.tfrecord files?

**Comment by dhingratul** [comment]
Fixed with re-running, error not reproducible.
