### ISSUE TITLE
Issue:  tensorflow.python.framework.errors_impl.NotFoundError: "/home/karen/cifar-10-batches-bin/"; No such file or directory

### ISSUE THREAD

**Issue by LutetiumX** [Tencent/PocketFlow#5]
Hardware: Intel Xeon CPU, M2000M Nvidia GPU, 64G RAM
Operating System: Ubuntu 16.04

Environment:  
- tensorflow==1.10.1
- Anaconda Python 3.6.6
- pandas == 0.23.4
- scikit-learn==0.20.0

Issue:
Not found: "/home/karen/cifar-10-batches-bin/"; No such file or directory

Trace:
```
2018-11-03 22:53:28.578113: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at matching_files_op.cc:49 : Not found: "/home/karen/cifar-10-batches-bin/"; No such file or directory
2018-11-03 22:53:28.578582: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at matching_files_op.cc:49 : Not found: "/home/karen/cifar-10-batches-bin/"; No such file or directory
2018-11-03 22:53:28.578636: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at iterator_ops.cc:910 : Not found: "/home/karen/cifar-10-batches-bin/"; No such file or directory
         [[Node: ShuffleDataset/data/MatchingFiles = MatchingFiles[](ShuffleDataset/data/MatchingFiles/pattern)]]
Traceback (most recent call last):
  File "/home/karen/anaconda3/envs/PocketFlow/lib/python3.6/site-packages/tensorflow/python/client/session.py",line 1278, in _do_call
    return fn(*args)
  File "/home/karen/anaconda3/envs/PocketFlow/lib/python3.6/site-packages/tensorflow/python/client/session.py",line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/karen/anaconda3/envs/PocketFlow/lib/python3.6/site-packages/tensorflow/python/client/session.py",line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: "/home/karen/cifar-10-batches-bin/"; No such file or directory
         [[Node: ShuffleDataset/data/MatchingFiles = MatchingFiles[](ShuffleDataset/data/MatchingFiles/pattern)]]
         [[Node: data/OneShotIterator = OneShotIterator[container="", dataset_factory=_make_dataset_zMNwdOMmCuY[], output_shapes=[[?,32,32,3], [?,10]], output_types=[DT_FLOAT, DT_FLOAT], shared_name="", _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 69, in <module>
    tf.app.run()
  File "/home/karen/anaconda3/envs/PocketFlow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 55, in main
    learner.train()
  File "/home/karen/workspace/sideprojects/PocketFlow/learners/full_precision/learner.py", line 71, in train
    self.sess_train.run(self.train_op)
  File "/home/karen/anaconda3/envs/PocketFlow/lib/python3.6/site-packages/tensorflow/python/client/session.py",line 877, in run
    run_metadata_ptr)
  File "/home/karen/anaconda3/envs/PocketFlow/lib/python3.6/site-packages/tensorflow/python/client/session.py",line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/karen/anaconda3/envs/PocketFlow/lib/python3.6/site-packages/tensorflow/python/client/session.py",line 1272, in _do_run
    run_metadata)
  File "/home/karen/anaconda3/envs/PocketFlow/lib/python3.6/site-packages/tensorflow/python/client/session.py",line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: "/home/karen/cifar-10-batches-bin/"; No such file or directory
         [[Node: ShuffleDataset/data/MatchingFiles = MatchingFiles[](ShuffleDataset/data/MatchingFiles/pattern)]]
         [[Node: data/OneShotIterator = OneShotIterator[container="", dataset_factory=_make_dataset_zMNwdOMmCuY[], output_shapes=[[?,32,32,3], [?,10]], output_types=[DT_FLOAT, DT_FLOAT], shared_name="", _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]
```
I checked with terminal ```/home/karen/cifar-10-batches-bin exists`` with the ```ls```:
```
ls cifar-10-batches-bin/
batches.meta.txt  data_batch_2.bin  data_batch_4.bin  readme.html
data_batch_1.bin  data_batch_3.bin  data_batch_5.bin  test_batch.bin
```
path.conf configuration:

```data_dir_local_cifar10 = "/home/karen/cifar-10-batches-bin/"```

I ran ```./scripts/run_local.sh nets/resnet_at_cifar10_run.py```

**Comment by LutetiumX** [comment]
Can we also have a requirements.txt file or environment.yml file? :)

**Comment by jiaxiang-wu** [comment]
Hi, can you try to replace this line in your configuration file:
```
data_dir_local_cifar10 = "/home/karen/cifar-10-batches-bin/"
```
with
```
data_dir_local_cifar10 = /home/karen/cifar-10-batches-bin/
```
which removes the double quotation marks.

**Comment by jiaxiang-wu** [comment]
Hi @LutetiumX 
Could you please confirm whether removing double quotation marks has resolved your problem? This could be helpful for other users.

**Comment by LutetiumX** [comment]
Yes, this has solved the problem.
