### ISSUE TITLE
I can't convert model compressed by uniform-tf to pb or tflite？

### ISSUE THREAD

**Issue by sunzhe09** [Tencent/PocketFlow#62]
here is the log：
(tf19_py36) trainer@8ef6e870703b:/data/raid/PocketFlow$ python tools/conversion/export_pb_tflite_models.py  --model_dir models_uqtf_eval --input_coll images_final --output_coll logits_final --quantize True
models_uqtf_eval/model.ckpt.meta
input_coll images_final
2018-11-15 03:42:15.304864: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-15 03:42:16.062860: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:07:00.0
totalMemory: 15.77GiB freeMemory: 15.36GiB
2018-11-15 03:42:16.062901: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2018-11-15 03:42:16.405597: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-15 03:42:16.405639: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 
2018-11-15 03:42:16.405647: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N 
2018-11-15 03:42:16.406072: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14863 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:07:00.0, compute capability: 7.0)
INFO:tensorflow:Restoring parameters from models_uqtf_eval/model.ckpt
INFO:tensorflow:input: net_input:0 / output: net_output:0
INFO:tensorflow:input's shape: (?, 32, 32, 3)
INFO:tensorflow:output's shape: (?, 10)
2018-11-15 03:42:16.939263: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2018-11-15 03:42:16.939305: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-15 03:42:16.939327: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 
2018-11-15 03:42:16.939348: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N 
2018-11-15 03:42:16.939606: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14863 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:07:00.0, compute capability: 7.0)
INFO:tensorflow:Restoring parameters from models_uqtf_eval/model.ckpt
INFO:tensorflow:Froze 174 variables.
INFO:tensorflow:Converted 174 variables to const ops.
INFO:tensorflow:models_uqtf_eval/model_original.pb generated
INFO:tensorflow:models_uqtf_eval/model_original.pb -> models_uqtf_eval/model_original.tflite
2018-11-15 03:42:17.128311: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2018-11-15 03:42:17.128356: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-15 03:42:17.128380: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 
2018-11-15 03:42:17.128392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N 
2018-11-15 03:42:17.128658: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14863 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:07:00.0, compute capability: 7.0)
INFO:tensorflow:models_uqtf_eval/model_original.tflite generated
2018-11-15 03:42:23.058929: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2018-11-15 03:42:23.058986: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-15 03:42:23.059007: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 
2018-11-15 03:42:23.059015: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N 
2018-11-15 03:42:23.059367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14863 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:07:00.0, compute capability: 7.0)
INFO:tensorflow:input: import/net_input:0 / output: import/net_output:0
Optimizing fused batch norm node name: "import/quant_model/resnet_model/batch_normalization_16/FusedBatchNorm"
op: "FusedBatchNorm"
input: "import/quant_model/resnet_model/conv2d_19/act_quant/FakeQuantWithMinMaxVars"
input: "import/quant_model/resnet_model/batch_normalization_16/gamma"
input: "import/quant_model/resnet_model/batch_normalization_16/beta"
input: "import/quant_model/resnet_model/batch_normalization_16/moving_mean"
input: "import/quant_model/resnet_model/batch_normalization_16/moving_variance"
device: "/job:localhost/replica:0/task:0/device:GPU:0"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "data_format"
  value {
    s: "NHWC"
  }
}
attr {
  key: "epsilon"
  value {
    f: 1.001e-05
  }
}
attr {
  key: "is_training"
  value {
    b: false
  }
}

Optimizing fused batch norm node name: "import/quant_model/resnet_model/batch_normalization_14/FusedBatchNorm"
op: "FusedBatchNorm"
input: "import/quant_model/resnet_model/conv2d_17/act_quant/FakeQuantWithMinMaxVars"
input: "import/quant_model/resnet_model/batch_normalization_14/gamma"
input: "import/quant_model/resnet_model/batch_normalization_14/beta"
input: "import/quant_model/resnet_model/batch_normalization_14/moving_mean"
input: "import/quant_model/resnet_model/batch_normalization_14/moving_variance"
device: "/job:localhost/replica:0/task:0/device:GPU:0"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "data_format"
  value {
    s: "NHWC"
  }
}
attr {
  key: "epsilon"
  value {
    f: 1.001e-05
  }
}
attr {
  key: "is_training"
  value {
    b: false
  }
}

Optimizing fused batch norm node name: "import/quant_model/resnet_model/batch_normalization_10/FusedBatchNorm"
op: "FusedBatchNorm"
input: "import/quant_model/resnet_model/conv2d_12/act_quant/FakeQuantWithMinMaxVars"
input: "import/quant_model/resnet_model/batch_normalization_10/gamma"
input: "import/quant_model/resnet_model/batch_normalization_10/beta"
input: "import/quant_model/resnet_model/batch_normalization_10/moving_mean"
input: "import/quant_model/resnet_model/batch_normalization_10/moving_variance"
device: "/job:localhost/replica:0/task:0/device:GPU:0"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "data_format"
  value {
    s: "NHWC"
  }
}
attr {
  key: "epsilon"
  value {
    f: 1.001e-05
  }
}
attr {
  key: "is_training"
  value {
    b: false
  }
}

Optimizing fused batch norm node name: "import/quant_model/resnet_model/batch_normalization_8/FusedBatchNorm"
op: "FusedBatchNorm"
input: "import/quant_model/resnet_model/conv2d_10/act_quant/FakeQuantWithMinMaxVars"
input: "import/quant_model/resnet_model/batch_normalization_8/gamma"
input: "import/quant_model/resnet_model/batch_normalization_8/beta"
input: "import/quant_model/resnet_model/batch_normalization_8/moving_mean"
input: "import/quant_model/resnet_model/batch_normalization_8/moving_variance"
device: "/job:localhost/replica:0/task:0/device:GPU:0"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "data_format"
  value {
    s: "NHWC"
  }
}
attr {
  key: "epsilon"
  value {
    f: 1.001e-05
  }
}
attr {
  key: "is_training"
  value {
    b: false
  }
}

Optimizing fused batch norm node name: "import/quant_model/resnet_model/batch_normalization_4/FusedBatchNorm"
op: "FusedBatchNorm"
input: "import/quant_model/resnet_model/conv2d_5/act_quant/FakeQuantWithMinMaxVars"
input: "import/quant_model/resnet_model/batch_normalization_4/gamma"
input: "import/quant_model/resnet_model/batch_normalization_4/beta"
input: "import/quant_model/resnet_model/batch_normalization_4/moving_mean"
input: "import/quant_model/resnet_model/batch_normalization_4/moving_variance"
device: "/job:localhost/replica:0/task:0/device:GPU:0"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "data_format"
  value {
    s: "NHWC"
  }
}
attr {
  key: "epsilon"
  value {
    f: 1.001e-05
  }
}
attr {
  key: "is_training"
  value {
    b: false
  }
}

Optimizing fused batch norm node name: "import/quant_model/resnet_model/batch_normalization_2/FusedBatchNorm"
op: "FusedBatchNorm"
input: "import/quant_model/resnet_model/conv2d_3/act_quant/FakeQuantWithMinMaxVars"
input: "import/quant_model/resnet_model/batch_normalization_2/gamma"
input: "import/quant_model/resnet_model/batch_normalization_2/beta"
input: "import/quant_model/resnet_model/batch_normalization_2/moving_mean"
input: "import/quant_model/resnet_model/batch_normalization_2/moving_variance"
device: "/job:localhost/replica:0/task:0/device:GPU:0"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "data_format"
  value {
    s: "NHWC"
  }
}
attr {
  key: "epsilon"
  value {
    f: 1.001e-05
  }
}
attr {
  key: "is_training"
  value {
    b: false
  }
}

Optimizing fused batch norm node name: "import/quant_model/resnet_model/batch_normalization/FusedBatchNorm"
op: "FusedBatchNorm"
input: "import/quant_model/resnet_model/conv2d/Conv2D"
input: "import/quant_model/resnet_model/batch_normalization/gamma"
input: "import/quant_model/resnet_model/batch_normalization/beta"
input: "import/quant_model/resnet_model/batch_normalization/moving_mean"
input: "import/quant_model/resnet_model/batch_normalization/moving_variance"
device: "/job:localhost/replica:0/task:0/device:GPU:0"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "data_format"
  value {
    s: "NHWC"
  }
}
attr {
  key: "epsilon"
  value {
    f: 1.001e-05
  }
}
attr {
  key: "is_training"
  value {
    b: false
  }
}

Optimizing fused batch norm node name: "import/quant_model/resnet_model/batch_normalization_6/FusedBatchNorm"
op: "FusedBatchNorm"
input: "import/quant_model/resnet_model/conv2d_7/act_quant/FakeQuantWithMinMaxVars"
input: "import/quant_model/resnet_model/batch_normalization_6/gamma"
input: "import/quant_model/resnet_model/batch_normalization_6/beta"
input: "import/quant_model/resnet_model/batch_normalization_6/moving_mean"
input: "import/quant_model/resnet_model/batch_normalization_6/moving_variance"
device: "/job:localhost/replica:0/task:0/device:GPU:0"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "data_format"
  value {
    s: "NHWC"
  }
}
attr {
  key: "epsilon"
  value {
    f: 1.001e-05
  }
}
attr {
  key: "is_training"
  value {
    b: false
  }
}

Optimizing fused batch norm node name: "import/quant_model/resnet_model/batch_normalization_12/FusedBatchNorm"
op: "FusedBatchNorm"
input: "import/quant_model/resnet_model/conv2d_14/act_quant/FakeQuantWithMinMaxVars"
input: "import/quant_model/resnet_model/batch_normalization_12/gamma"
input: "import/quant_model/resnet_model/batch_normalization_12/beta"
input: "import/quant_model/resnet_model/batch_normalization_12/moving_mean"
input: "import/quant_model/resnet_model/batch_normalization_12/moving_variance"
device: "/job:localhost/replica:0/task:0/device:GPU:0"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "data_format"
  value {
    s: "NHWC"
  }
}
attr {
  key: "epsilon"
  value {
    f: 1.001e-05
  }
}
attr {
  key: "is_training"
  value {
    b: false
  }
}

Optimizing fused batch norm node name: "import/quant_model/resnet_model/batch_normalization_18/FusedBatchNorm"
op: "FusedBatchNorm"
input: "import/quant_model/resnet_model/conv2d_21/act_quant/FakeQuantWithMinMaxVars"
input: "import/quant_model/resnet_model/batch_normalization_18/gamma"
input: "import/quant_model/resnet_model/batch_normalization_18/beta"
input: "import/quant_model/resnet_model/batch_normalization_18/moving_mean"
input: "import/quant_model/resnet_model/batch_normalization_18/moving_variance"
device: "/job:localhost/replica:0/task:0/device:GPU:0"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "data_format"
  value {
    s: "NHWC"
  }
}
attr {
  key: "epsilon"
  value {
    f: 1.001e-05
  }
}
attr {
  key: "is_training"
  value {
    b: false
  }
}

INFO:tensorflow:outputs from the *.pb model: [[ 0.09550263  0.02136519  0.09638907  0.2240788   0.05516921  0.2050214
   0.16269687  0.01081822  0.1107803   0.01817832]]
Didn't find custom op for name 'FAKE_QUANT' with version 1

Registration failed.

2018-11-15 03:42:24.739825: E tensorflow/contrib/lite/python/interpreter_wrapper/interpreter_wrapper.cc:137] Cannot allocate tensors: invalid interpreter.
Traceback (most recent call last):
  File "tools/conversion/export_pb_tflite_models.py", line 294, in main
    export_pb_tflite_model(net, file_path_meta, file_path_pb, file_path_tflite, edit_graph=False)
  File "tools/conversion/export_pb_tflite_models.py", line 267, in export_pb_tflite_model
    test_tflite_model(file_path_tflite, net['input_data'])
  File "tools/conversion/export_pb_tflite_models.py", line 122, in test_tflite_model
    interpreter.allocate_tensors()
  File "/home/trainer/anaconda3/envs/tf19_py36/lib/python3.6/site-packages/tensorflow/contrib/lite/python/interpreter.py", line 68, in allocate_tensors
    raise ValueError('Failed to allocate tensors')
ValueError: Failed to allocate tensors

**Comment by jiaxiang-wu** [comment]
Hi, which model are you using? ResNet or MobileNet-v1/v2?

**Comment by jiaxiang-wu** [comment]
@sunzhe09 Any updates?

**Comment by sunzhe09** [comment]
it's my fault,i have fixed it!
