### ISSUE TITLE
Parameter Shape Error for non-uniform Quantization  

### ISSUE THREAD

**Issue by ylfzr** [Tencent/PocketFlow#76]
**Describe the bug**
When set FLAGS.nuql_opt_mode to be 'both', that is, learn both the weights and the cluster centers. An error occur if enable rl agents.

**To Reproduce**
1. Enable rl agent, set FLAGS.nuql_opt_mode to be 'both'.
2. The first rl roll-out works normally. 
3. The second rl roll-out starts, new compressing policy given, start to quantize model using thee new policy.
4. See error:
Traceback (most recent call last):
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Parameters and update must be the same size
         [[Node: Adam/update_model/resnet_model/conv2d_57/Conv2D/nonuniform_quantize/clusters/AssignSub = AssignSub[T=DT_FLOAT, use_locking=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model/resnet_model/conv2d_57/Conv2D/nonuniform_quantize/clusters, Adam/update_model/resnet_model/conv2d_57/Conv2D/nonuniform_quantize/clusters/truediv_1)]]
         [[Node: Adam/update/_2788 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_42493_Adam/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nets/resnet_at_cifar10_run.py", line 69, in <module>
    tf.app.run()
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "nets/resnet_at_cifar10_run.py", line 51, in main
    learner = create_learner(sm_writer, model_helper)
  File "/home/wangjiaxing/workspaces/Projects/PocketFlow-pull/PocketFlow/learners/learner_utils.py", line 56, in create_learner
    learner = NonUniformQuantLearner(sm_writer, model_helper)
  File "/home/wangjiaxing/workspaces/Projects/PocketFlow-pull/PocketFlow/learners/nonuniform_quantization/learner.py", line 115, in __init__
    self.optimal_w_bit_list, self.optimal_a_bit_list = bit_optimizer.run()
  File "/home/wangjiaxing/workspaces/Projects/PocketFlow-pull/PocketFlow/learners/nonuniform_quantization/bit_optimizer.py", line 138, in run
    optimal_w_bits, optimal_a_bits = self.__calc_optimal_bits()
  File "/home/wangjiaxing/workspaces/Projects/PocketFlow-pull/PocketFlow/learners/nonuniform_quantization/bit_optimizer.py", line 173, in __calc_optimal_bits
    arranged_layer_bits)
  File "/home/wangjiaxing/workspaces/Projects/PocketFlow-pull/PocketFlow/learners/nonuniform_quantization/bit_optimizer.py", line 245, in __calc_rollout_reward
    self.__global_finetune(feed_dict_train)
  File "/home/wangjiaxing/workspaces/Projects/PocketFlow-pull/PocketFlow/learners/nonuniform_quantization/bit_optimizer.py", line 281, in __global_finetune
    _ = self.sess_train.run(self.ops['train'], feed_dict=feed_dict_train)
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Parameters and update must be the same size
         [[Node: Adam/update_model/resnet_model/conv2d_57/Conv2D/nonuniform_quantize/clusters/AssignSub = AssignSub[T=DT_FLOAT, use_locking=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model/resnet_model/conv2d_57/Conv2D/nonuniform_quantize/clusters, Adam/update_model/resnet_model/conv2d_57/Conv2D/nonuniform_quantize/clusters/truediv_1)]]
         [[Node: Adam/update/_2788 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_42493_Adam/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Adam/update_model/resnet_model/conv2d_57/Conv2D/nonuniform_quantize/clusters/AssignSub', defined at:
  File "nets/resnet_at_cifar10_run.py", line 69, in <module>
    tf.app.run()
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "nets/resnet_at_cifar10_run.py", line 51, in main
    learner = create_learner(sm_writer, model_helper)
  File "/home/wangjiaxing/workspaces/Projects/PocketFlow-pull/PocketFlow/learners/learner_utils.py", line 56, in create_learner
    learner = NonUniformQuantLearner(sm_writer, model_helper)
  File "/home/wangjiaxing/workspaces/Projects/PocketFlow-pull/PocketFlow/learners/nonuniform_quantization/learner.py", line 95, in __init__
    self.__build_train()  # for train
  File "/home/wangjiaxing/workspaces/Projects/PocketFlow-pull/PocketFlow/learners/nonuniform_quantization/learner.py", line 274, in __build_train
    self.ops['train'] = optimizer.apply_gradients(grads, global_step=self.ft_step)
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 605, in apply_gradients
    update_ops.append(processor.update_op(self, grad))
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 127, in update_op
    return optimizer._apply_sparse_duplicate_indices(g, self._v)
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 1014, in _apply_sparse_duplicate_indices
    return self._apply_sparse(gradient_no_duplicate_indices, var)
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/training/adam.py", line 207, in _apply_sparse
    lambda x, i, v: state_ops.scatter_add(  # pylint: disable=g-long-lambda
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/training/adam.py", line 201, in _apply_sparse_shared
    use_locking=self._use_locking)
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 154, in assign_sub
    ref, value, use_locking=use_locking, name=name)
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 143, in assign_sub
    "AssignSub", ref=ref, value=value, use_locking=use_locking, name=name)
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/wangjiaxing/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Parameters and update must be the same size
         [[Node: Adam/update_model/resnet_model/conv2d_57/Conv2D/nonuniform_quantize/clusters/AssignSub = AssignSub[T=DT_FLOAT, use_locking=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model/resnet_model/conv2d_57/Conv2D/nonuniform_quantize/clusters, Adam/update_model/resnet_model/conv2d_57/Conv2D/nonuniform_quantize/clusters/truediv_1)]]
         [[Node: Adam/update/_2788 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_42493_Adam/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Expected behavior**
No Error Occur, quantization can go on normally

**Screenshots**
![image](https://user-images.githubusercontent.com/22250974/48657002-fbfc9b80-ea66-11e8-9258-2e372ba28f8a.png)

**Desktop (please complete the following information):**
 - OS: CentOs
 - Browser chrome
 - Version None

**Additional context**
The problem is caused by change of shape of 'clusters' variables. Recall that with different compressing policy given by the rl agent,   'clusters' variables' shape changes as using different bit number means different number of clustering centers.  Although in line 297, learners/nonuniform_quantization/utils.py,  'validate_shape' of the cluster variables has been set to False. Corrresponding slot variables created in the Adam optimizer still keeps the last-roll-out-time varaible shape, causing the problem.  One way to bypass this Error is to change the Adam optimizer in line 248, learners/nonuniform_quantization/learner.py to GradientDesecentOptimizer which does not maintain slot variables. PR with a naive solution has been sent.

**Comment by jiaxiang-wu** [comment]
Resolved in the pull request #81
